/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: CGI Tutorials (https://sketchfab.com/cgitutorials)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lego-starfighter-1da8224a800a420b93afced474aced1d
title: Lego Starfighter
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceShip6(props) {
  const { nodes, materials } = useGLTF('/spaceship6.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.36, -0.13, 0.25]} scale={0.7}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <mesh geometry={nodes.polySurface341_orange_0.geometry} material={materials.orange} />
            <mesh geometry={nodes.polySurface341_glass_blue_0.geometry} material={materials.glass_blue} />
            <mesh geometry={nodes.polySurface341_GreyYellow_0.geometry} material={materials.GreyYellow} />
            <mesh geometry={nodes.polySurface341_greydark_0.geometry} material={materials.greydark} />
            <mesh geometry={nodes.polySurface341_greydark_0_1.geometry} material={materials.greydark} />
            <mesh geometry={nodes.polySurface341_Lego_Black_0.geometry} material={materials.Lego_Black} />
            <mesh geometry={nodes.polySurface341_greylight_0.geometry} material={materials.greylight} />
            <mesh geometry={nodes.polySurface341_black_0.geometry} material={materials.black} />
            <mesh geometry={nodes.polySurface341_Lego_White_0.geometry} material={materials.Lego_White} />
            <mesh geometry={nodes.polySurface341_BlueGlow_0.geometry} material={materials.BlueGlow} />
            <mesh geometry={nodes.polySurface341_redglass_0.geometry} material={materials.redglass} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship6.gltf')
