/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Valery Kharitonov (https://sketchfab.com/KJLOYH)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/xian-spaceship-0c414ddf4dfa419983ae5574da3a5242
title: Xian SpaceShip
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceShip0(props) {
  const { nodes, materials } = useGLTF('/spaceship0.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[131.12, 160.99, -209.42]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.TopGun1_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[-232.74, 76.72, -1.93]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.Tail_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[185.3, 24.65, -303.18]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.FrontMovement_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[360.96, 34.44, -435.15]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TurbineFront_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[231.29, 41.28, -554.51]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.FrontWing_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[102.92, 24.34, -282.38]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BackMovement_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[197.45, 28.29, -271]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BindingRight_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[-158.02, 110.69, -437.32]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BackWing_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[385.32, -114.65, -1.93]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.BottomBody_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[445.11, 6.67, -1.94]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.Cabin_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[-58.46, 134.22, -399]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TurbineBack_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[323.28, -155.43, -55.61]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.BottomGun1_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[185.3, 24.65, 299.22]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.FrontMovement2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[360.96, 34.44, 431.19]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TurbineFront2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[258.03, 41.28, 582.36]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.FrontWing2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[102.92, 24.34, 278.42]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BackMovement2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[197.45, 28.29, 267.04]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BindingLeft_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[-158.02, 110.69, 433.36]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.BackWing2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[-58.46, 134.22, 395.05]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TurbineBack2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[323.28, -155.43, 45.23]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.BottomGun2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[131.12, 160.99, 205.61]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.TopGun2_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[270.11, 100.3, 96.51]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.FrontLight_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
          <group position={[92.82, -33.97, -1.93]} rotation={[-Math.PI / 2, 0.05, 0]} scale={100}>
            <mesh geometry={nodes.MainBody_low_UV001_0.geometry} material={materials['UV.001']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship0.gltf')
