/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ruslan Malovsky (https://sketchfab.com/malovsky)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-spaceship-unitron-20a3bf99baf943f2887cb586b5195224
title: Free Spaceship Unitron
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceShip1(props) {
  const { nodes, materials } = useGLTF('/spaceship1.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Spaceship_Osn_0.geometry} material={materials.material} />
            <mesh geometry={nodes.Spaceship_Turbine_0.geometry} material={materials.Turbine} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship1.gltf')
