/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: 雨先森 (https://sketchfab.com/yutiansax)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/709e177cb2d346cca165ffd8f2fa58be
title: 朋克飞车
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function SpaceShip3(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/spaceship3.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="_222">
                <group name="bone_221" position={[-0.03, 1.38, -0.54]}>
                  <group name="cube_0" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_1" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_2" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_3" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_4" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_5" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_6" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_7" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_8" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_9" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_10" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_11" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_12" position={[0.01, -0.74, -0.23]} rotation={[-0.28, 0, 0]}>
                    <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_13" position={[0.01, -0.74, -0.23]} rotation={[-0.28, 0, 0]}>
                    <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_14" position={[0.01, -0.74, -0.23]} rotation={[-0.28, 0, 0]}>
                    <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_15" position={[0.01, -0.74, -0.23]} rotation={[-0.28, 0, 0]}>
                    <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_16" position={[0.01, -0.74, -0.23]} rotation={[-0.28, 0, 0]}>
                    <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_17" position={[0.01, -0.74, -0.23]} rotation={[-0.14, 0, 0]}>
                    <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_18" position={[0.01, -0.74, -0.23]} rotation={[-0.14, 0, 0]}>
                    <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_19" position={[0.01, -0.74, -0.23]} rotation={[-0.14, 0, 0]}>
                    <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_20" position={[0.01, -0.74, -0.23]} rotation={[-0.14, 0, 0]}>
                    <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_21" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.7]}>
                    <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_22" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.7]}>
                    <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_23" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_24" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_25" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_26" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_27" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 6, 0, 0]}>
                    <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_28" position={[0.03, -0.13, -0.85]} rotation={[1.61, Math.PI / 10, 0]}>
                    <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_29" position={[0.03, -0.13, -0.85]} rotation={[1.61, -Math.PI / 10, 0]}>
                    <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_30" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_31" position={[0.01, -0.74, -0.23]} rotation={[0, -0.34, 0]}>
                    <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_32" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_33" position={[-0.53, -0.74, 1.24]} rotation={[0.88, 0, 0]}>
                    <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_34" position={[0.02, -0.74, 1.24]} rotation={[0.18, 0, 0]}>
                    <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_35" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_36" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_37" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_38" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_39" position={[0.01, -0.74, -0.23]} rotation={[-0.17, -0.2, -0.72]}>
                    <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_40" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.19]}>
                    <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_41" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.87]}>
                    <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_42" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.87]}>
                    <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_43" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.19]}>
                    <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_44" position={[0.01, -0.74, -0.23]} rotation={[0.17, 0, 0]}>
                    <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_45" position={[0.01, -0.74, -0.23]} rotation={[0.17, 0, 0]}>
                    <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_46" position={[0.01, -0.74, -0.23]} rotation={[0.17, 0, -0.44]}>
                    <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_47" position={[0.05, -0.74, -0.23]} rotation={[0.17, 0, 0.44]}>
                    <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_48" position={[0.01, -0.74, -0.23]} rotation={[0.65, 0, 0]}>
                    <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_49" position={[0.01, -0.74, -0.23]} rotation={[0.13, 0, 0]}>
                    <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_50" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_51" position={[0.01, -0.74, -0.23]} rotation={[0, -0.51, -0.49]}>
                    <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_52" position={[0.01, -0.74, -0.23]} rotation={[0, 0.51, 0.49]}>
                    <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_53" position={[0.01, -0.74, -0.23]} rotation={[0, -0.51, -0.49]}>
                    <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_54" position={[0.01, -0.74, -0.23]} rotation={[0, 0.51, 0.49]}>
                    <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_55" position={[0.01, -0.74, -0.23]} rotation={[0.13, 0, -Math.PI / 5]}>
                    <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_56" position={[0.05, -0.74, -0.23]} rotation={[0.13, 0, Math.PI / 5]}>
                    <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_57" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.4]}>
                    <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_58" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.4]}>
                    <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_59" position={[0.01, -0.74, -0.23]} rotation={[0.09, -0.01, -0.22]}>
                    <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_60" position={[0.01, -0.74, -0.23]} rotation={[0.55, -0.11, -0.19]}>
                    <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_61" position={[0.01, -0.74, -0.23]} rotation={[-0.48, 0.11, -0.19]}>
                    <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_62" position={[0.01, -0.74, -0.23]} rotation={[-0.24, -0.01, -0.22]}>
                    <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_63" position={[0.01, -0.74, -0.23]} rotation={[0.22, -0.11, -0.19]}>
                    <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_64" position={[0.01, -0.74, -0.23]} rotation={[-0.81, 0.11, -0.19]}>
                    <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_65" position={[0.01, -0.74, -0.23]} rotation={[-0.24, 0.01, 0.22]}>
                    <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_66" position={[0.01, -0.74, -0.23]} rotation={[-0.81, -0.11, 0.19]}>
                    <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_67" position={[0.01, -0.74, -0.23]} rotation={[0.22, 0.11, 0.19]}>
                    <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_68" position={[0.01, -0.74, -0.23]} rotation={[0.55, 0.11, 0.19]}>
                    <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_69" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0.01, 0.22]}>
                    <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_70" position={[0.01, -0.74, -0.23]} rotation={[-0.48, -0.11, 0.19]}>
                    <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_71" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_72" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_73" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_74" position={[0.01, -0.74, -0.23]} rotation={[-0.17, 0, 0]}>
                    <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_75" position={[0.01, -0.74, -0.23]} rotation={[-0.17, 0, 0]}>
                    <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_76" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_77" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_78" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, 0]}>
                    <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_79" position={[0.01, -0.74, -0.23]} rotation={[0.13, 0, 0]}>
                    <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_80" position={[0.01, -0.74, -0.23]} rotation={[0.13, 0, 0]}>
                    <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_81" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_82" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_83" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_84" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_85" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_86" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_87" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_88" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_89" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -0.84]}>
                    <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_90" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_91" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_92" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.84]}>
                    <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_93" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_94" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_95" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_96" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_97" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_98" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_99" position={[0.01, -0.74, -0.23]} rotation={[0.09, 0, 0]}>
                    <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_100" position={[0.01, -0.74, -0.23]} rotation={[-0.07, 0, 0]}>
                    <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_101" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_102" position={[0.01, -0.74, -0.23]} rotation={[0, 0, Math.PI / 10]}>
                    <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_103" position={[0.01, -0.74, -0.23]} rotation={[0, 0, -Math.PI / 10]}>
                    <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_104" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_105" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_106" position={[0.01, -0.74, -0.23]} rotation={[-0.44, 0, 0]}>
                    <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_107" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_108" position={[0.01, -0.74, -0.23]} rotation={[0.96, 0, 0]}>
                    <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_109" position={[0.01, -0.74, -0.23]} rotation={[0.96, 0, 0]}>
                    <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_110" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_111" position={[0.01, -0.74, -0.23]} rotation={[-0.57, 0, 0]}>
                    <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_112" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_113" position={[0.01, -0.74, -0.23]} rotation={[-0.57, 0, 0]}>
                    <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_114" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_115" position={[0.01, -0.74, -0.23]} rotation={[-0.57, 0, 0]}>
                    <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_116" position={[0.01, -0.74, -0.23]} rotation={[-0.57, 0, 0]}>
                    <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_117" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_118" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_119" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_120" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_121" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_122" position={[0.01, -0.74, -0.23]} rotation={[0.44, 0.2, 0]}>
                    <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_123" position={[0.01, -0.74, -0.23]} rotation={[-0.52, -0.3, -0.05]}>
                    <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_124" position={[0.01, -0.74, -0.23]} rotation={[-0.02, -0.14, -0.18]}>
                    <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_125" position={[0.01, -0.74, -0.23]} rotation={[0.03, 0.15, -0.18]}>
                    <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_126" position={[0.01, -0.74, -0.23]} rotation={[-0.03, -0.16, 0.84]}>
                    <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_127" position={[0.01, -0.74, -0.23]} rotation={[0.03, 0.15, 0.92]}>
                    <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_128" position={[0.01, -0.74, -0.23]} rotation={[0.03, -0.15, -0.92]}>
                    <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_129" position={[0.01, -0.74, -0.23]} rotation={[-0.09, 0, 0.93]}>
                    <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_130" position={[0.01, -0.74, -0.23]} rotation={[0.26, 0.1, 0.84]}>
                    <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_131" position={[0.01, -0.74, -0.23]} rotation={[0.19, 0.15, 0.68]}>
                    <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_132" position={[0.01, -0.74, -0.23]} rotation={[0.19, -0.15, -0.68]}>
                    <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_133" position={[0.01, -0.74, -0.23]} rotation={[0.8, 0.27, 0.67]}>
                    <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_134" position={[0.01, -0.74, -0.23]} rotation={[0.8, -0.27, -0.67]}>
                    <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_135" position={[0.01, -0.74, -0.23]} rotation={[0.26, -0.1, -0.84]}>
                    <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_136" position={[0.01, -0.74, -0.23]} rotation={[-0.09, 0, -0.93]}>
                    <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_137" position={[0.01, -0.74, -0.23]} rotation={[-0.52, 0.3, 0.05]}>
                    <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_138" position={[0.01, -0.74, -0.23]} rotation={[0.22, 0.13, 0.84]}>
                    <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_139" position={[0.01, -0.74, -0.23]} rotation={[0.22, -0.13, -0.84]}>
                    <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_140" position={[0.01, -0.74, -0.23]} rotation={[0, -0.22, 0]}>
                    <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_141" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_142" position={[0.01, -0.74, -0.23]}>
                    <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_143" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.4]}>
                    <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_144" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, Math.PI / 5]}>
                    <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_145" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, Math.PI / 5]}>
                    <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_146" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, -Math.PI / 5]}>
                    <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_147" position={[0.01, -0.74, -0.23]} rotation={[Math.PI / 8, 0, -Math.PI / 5]}>
                    <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_148" position={[0.01, -0.74, -0.23]} rotation={[0, 0, 0.4]}>
                    <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_149" position={[0.01, -0.74, -0.23]} rotation={[0, 0.22, 0]}>
                    <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_150" position={[0.01, -0.74, -0.23]} rotation={[-0.02, 0.14, 0.18]}>
                    <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_151" position={[0.01, -0.74, -0.23]} rotation={[-0.03, 0.16, -0.84]}>
                    <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_152" position={[0.01, -0.74, -0.23]} rotation={[0.03, -0.15, 0.18]}>
                    <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_153" position={[0.01, -0.74, -0.23]} rotation={[0.44, -0.2, 0]}>
                    <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_154" position={[0.01, -0.74, -0.23]} rotation={[-0.07, 0, 0]}>
                    <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_155" position={[0.01, -0.74, -0.23]} rotation={[0.58, 0, 0]}>
                    <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_156" position={[0.01, -0.74, -0.23]} rotation={[0.58, 0, 0]}>
                    <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_157" position={[0.01, -0.74, -0.23]} rotation={[0.08, 0, 0]}>
                    <mesh name="Object_320" geometry={nodes.Object_320.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_158" position={[0.01, -0.74, -0.23]} rotation={[0.08, 0, 0]}>
                    <mesh name="Object_322" geometry={nodes.Object_322.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_159" position={[0.01, -0.74, -0.23]} rotation={[0.29, 0, 0]}>
                    <mesh name="Object_324" geometry={nodes.Object_324.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_160" position={[0.01, -0.74, -0.23]} rotation={[0.29, 0, 0]}>
                    <mesh name="Object_326" geometry={nodes.Object_326.geometry} material={materials.material_0} />
                  </group>
                  <group name="cube_161" position={[0.01, -0.74, -0.23]} rotation={[0.44, 0, 0]}>
                    <mesh name="Object_328" geometry={nodes.Object_328.geometry} material={materials.material_0} />
                  </group>
                  <group name="bone2_173" position={[1.48, -0.84, -2.82]}>
                    <group name="cube_162" position={[-1.47, 0.1, 2.59]} rotation={[0, 0, -Math.PI / 2]}>
                      <mesh name="Object_331" geometry={nodes.Object_331.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_163" position={[-1.47, 0.1, 2.59]} rotation={[0, 0, -Math.PI / 2]}>
                      <mesh name="Object_333" geometry={nodes.Object_333.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_164" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_335" geometry={nodes.Object_335.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_165" position={[-1.47, 0.1, 2.59]} rotation={[0, 0, 0.04]}>
                      <mesh name="Object_337" geometry={nodes.Object_337.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_166" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_339" geometry={nodes.Object_339.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_167" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_341" geometry={nodes.Object_341.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_168" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_343" geometry={nodes.Object_343.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_169" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_345" geometry={nodes.Object_345.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_170" position={[-1.47, 0.1, 2.59]}>
                      <mesh name="Object_347" geometry={nodes.Object_347.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_171" position={[-1.47, 0.1, 2.59]} rotation={[0, 0, -0.26]}>
                      <mesh name="Object_349" geometry={nodes.Object_349.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_172" position={[-1.47, 0.1, 2.59]} rotation={[0, 0, -0.26]}>
                      <mesh name="Object_351" geometry={nodes.Object_351.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="bone3_185" position={[-1.42, -0.84, -2.82]}>
                    <group name="cube_174" position={[1.42, 0.1, 2.59]} rotation={[0, 0, Math.PI / 2]}>
                      <mesh name="Object_354" geometry={nodes.Object_354.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_175" position={[1.42, 0.1, 2.59]} rotation={[0, 0, Math.PI / 2]}>
                      <mesh name="Object_356" geometry={nodes.Object_356.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_176" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_358" geometry={nodes.Object_358.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_177" position={[1.42, 0.1, 2.59]} rotation={[0, 0, -0.04]}>
                      <mesh name="Object_360" geometry={nodes.Object_360.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_178" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_362" geometry={nodes.Object_362.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_179" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_364" geometry={nodes.Object_364.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_180" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_366" geometry={nodes.Object_366.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_181" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_368" geometry={nodes.Object_368.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_182" position={[1.42, 0.1, 2.59]}>
                      <mesh name="Object_370" geometry={nodes.Object_370.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_183" position={[1.42, 0.1, 2.59]} rotation={[0, 0, 0.26]}>
                      <mesh name="Object_372" geometry={nodes.Object_372.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_184" position={[1.42, 0.1, 2.59]} rotation={[0, 0, 0.26]}>
                      <mesh name="Object_374" geometry={nodes.Object_374.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="zuoyi_195" position={[-0.5, -1.5, 2.6]}>
                    <group name="cube_186" position={[0.51, 0.76, -2.83]} rotation={[0.72, 0, 0]}>
                      <mesh name="Object_377" geometry={nodes.Object_377.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_187" position={[0.51, 0.76, -2.83]} rotation={[0.59, 0, 0]}>
                      <mesh name="Object_379" geometry={nodes.Object_379.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_188" position={[0.51, 0.76, -2.83]} rotation={[-0.87, 0, 0]}>
                      <mesh name="Object_381" geometry={nodes.Object_381.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_189" position={[0.51, 0.76, -2.83]}>
                      <mesh name="Object_383" geometry={nodes.Object_383.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_190" position={[0.51, 0.76, -2.83]}>
                      <mesh name="Object_385" geometry={nodes.Object_385.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_191" position={[0.51, 0.76, -2.83]} rotation={[-0.87, 0, 0]}>
                      <mesh name="Object_387" geometry={nodes.Object_387.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_192" position={[0.51, 0.76, -2.83]} rotation={[Math.PI / 6, 0, 0]}>
                      <mesh name="Object_389" geometry={nodes.Object_389.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_193" position={[0.51, 0.76, -2.83]}>
                      <mesh name="Object_391" geometry={nodes.Object_391.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_194" position={[0.51, 0.76, -2.83]}>
                      <mesh name="Object_393" geometry={nodes.Object_393.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="zuoyi2_205" position={[0.56, -1.5, 2.6]}>
                    <group name="cube_196" position={[-0.55, 0.76, -2.83]} rotation={[0.72, 0, 0]}>
                      <mesh name="Object_396" geometry={nodes.Object_396.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_197" position={[-0.55, 0.76, -2.83]} rotation={[0.59, 0, 0]}>
                      <mesh name="Object_398" geometry={nodes.Object_398.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_198" position={[-0.55, 0.76, -2.83]} rotation={[-0.87, 0, 0]}>
                      <mesh name="Object_400" geometry={nodes.Object_400.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_199" position={[-0.55, 0.76, -2.83]}>
                      <mesh name="Object_402" geometry={nodes.Object_402.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_200" position={[-0.55, 0.76, -2.83]}>
                      <mesh name="Object_404" geometry={nodes.Object_404.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_201" position={[-0.55, 0.76, -2.83]} rotation={[-0.87, 0, 0]}>
                      <mesh name="Object_406" geometry={nodes.Object_406.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_202" position={[-0.55, 0.76, -2.83]} rotation={[Math.PI / 6, 0, 0]}>
                      <mesh name="Object_408" geometry={nodes.Object_408.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_203" position={[-0.55, 0.76, -2.83]}>
                      <mesh name="Object_410" geometry={nodes.Object_410.geometry} material={materials.material_0} />
                    </group>
                    <group name="cube_204" position={[-0.55, 0.76, -2.83]}>
                      <mesh name="Object_412" geometry={nodes.Object_412.geometry} material={materials.material_0} />
                    </group>
                  </group>
                  <group name="deng_212" position={[1.11, -0.61, 1.77]}>
                    <group name="bone7_207" position={[0, 0.04, -0.31]}>
                      <group name="cube_206" position={[-1.11, -0.17, -1.69]} rotation={[0.13, 0, -Math.PI / 5]}>
                        <mesh name="Object_416" geometry={nodes.Object_416.geometry} material={materials.material_0} />
                      </group>
                    </group>
                    <group name="bone5_209">
                      <group name="cube_208" position={[-1.11, -0.13, -2]} rotation={[0.13, 0, -Math.PI / 5]}>
                        <mesh name="Object_419" geometry={nodes.Object_419.geometry} material={materials.material_0} />
                      </group>
                    </group>
                    <group name="bone8_211" position={[0, -0.04, 0.31]}>
                      <group name="cube_210" position={[-1.11, -0.09, -2.31]} rotation={[0.13, 0, -Math.PI / 5]}>
                        <mesh name="Object_422" geometry={nodes.Object_422.geometry} material={materials.material_0} />
                      </group>
                    </group>
                  </group>
                  <group name="deng2_219" position={[-1.05, -0.61, 1.77]}>
                    <group name="bone11_218" position={[0, -0.04, 0.31]}>
                      <group name="cube_217" position={[1.11, -0.09, -2.31]} rotation={[0.13, 0, Math.PI / 5]}>
                        <mesh name="Object_432" geometry={nodes.Object_432.geometry} material={materials.material_0} />
                      </group>
                    </group>
                    <group name="bone9_214" position={[0, 0.04, -0.31]}>
                      <group name="cube_213" position={[1.11, -0.17, -1.69]} rotation={[0.13, 0, Math.PI / 5]}>
                        <mesh name="Object_426" geometry={nodes.Object_426.geometry} material={materials.material_0} />
                      </group>
                    </group>
                    <group name="bone10_216">
                      <group name="cube_215" position={[1.11, -0.13, -2]} rotation={[0.13, 0, Math.PI / 5]}>
                        <mesh name="Object_429" geometry={nodes.Object_429.geometry} material={materials.material_0} />
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship3.gltf')
