/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Chin Eeyang (https://sketchfab.com/j22036609)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/fighter-spacecraft-21a84cc35eaf42e58d80312abb7e9991
title: Fighter Spacecraft
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SpaceShip4(props) {
  const { nodes, materials } = useGLTF('/spaceship4.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blinn6SG} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.blinn9SG} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.lambert2SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/spaceship4.gltf')
